#	Copyright(c) 2018-2022 Gluwa, Inc.
#
#	This file is part of Creditcoin.
#
#	Creditcoin is free software: you can redistribute it and/or modify
#	it under the terms of the GNU Lesser General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.
#
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#	GNU Lesser General Public License for more details.
#
#	You should have received a copy of the GNU Lesser General Public License
#	along with Creditcoin. If not, see <https://www.gnu.org/licenses/>.

#       This docker-compose file uses the following images below:
#
#       REPOSITORY                         TAG              IMAGE ID       SIZE
#       gluwa/creditcoin-consensus         1.8              af6dcd0cc96f   354MB
#       gluwa/creditcoin-processor         1.8              00e82ee83478   3.02GB
#       gluwa/sawtooth-rest-api            1.8              560f5c606bd2   225MB
#       gluwa/creditcoin-validator         1.8              ac70d1225218   403MB
#       gluwa/creditcoin-gateway           1.8              5585247d74f3   738MB
#
#       Built from:
#
#       Sawtooth-Core (validator/rest-api), https://github.com/gluwa/sawtooth-legacy-core/tree/dev:
#            - dev@4158e7c3dcd8dd8f987801af92f848ad684b3703
#        Creditcoin-Processor-Rust, https://github.com/gluwa/creditcoin-legacy-processor-rust/tree/dev:
#            - dev@dff18824dc287af7828e6cf4529704eb76c82eb7
#        Creditcoin-Consensus-Rust, https://github.com/gluwa/creditcoin-legacy-consensus-rust/tree/dev:
#            - dev@33903719f949d96f81d4dda9dd5269ced6868b64
#        Creditcoin-Gateway, https://github.com/gluwa/creditcoin-legacy-gateway/tree/dev:
#            - dev@e354f2e2a837f7408f5bba21f9a4fa015120b694, using ccplugin v1.1.2
version: "3.7"

services:

  settings-tp:
    image: hyperledger/sawtooth-settings-tp:1.2
    container_name: sawtooth-settings-tp
    depends_on:
      - validator
    entrypoint: settings-tp -C tcp://validator:4004
    stop_signal: SIGKILL
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"

  validator:
    image: gluwa/creditcoin-validator:1.8
    container_name: sawtooth-validator
    volumes:
      - type: volume
        source: validator-block-volume
        target: /var/lib/sawtooth/
      - type: volume
        source: validator-key-volume
        target: /etc/sawtooth/keys/
    expose:
      - 4004
      - 8800
      - 5050
    ports:
      - 4004:4004
      - 8800:8800
    secrets:
     - source: validator_logging
       target: /etc/sawtooth/log_config.toml
    entrypoint: |
        bash -c 'if [[ ! -f /etc/sawtooth/keys/validator.pub ]]
            then 
                echo "First run"
                sawadm keygen
            fi
            sawtooth-validator -vv \
                --endpoint tcp://[insert.your.ip]:8800 \
                --bind component:tcp://eth0:4004 \
                --bind network:tcp://eth0:8800 \
                --bind consensus:tcp://eth0:5050 \
                --peering dynamic \
                --seeds tcp://creditcoin-node.gluwa.com:8800 \
                --seeds tcp://creditcoin-gateway.gluwa.com:8800 \
                --scheduler serial \
                --state-pruning-block-depth 2000000'
    stop_signal: SIGKILL
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "100m"

  rest-api:
    image: gluwa/sawtooth-rest-api:1.8
    container_name: sawtooth-rest-api
    ports:
      - 8008:8008
    secrets:
     - source: rest_api_logging
       target: /etc/sawtooth/log_config.toml
    depends_on:
      - validator
    entrypoint: sawtooth-rest-api -vv -C tcp://validator:4004 --bind rest-api:8008
    stop_signal: SIGKILL
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"

  processor:
    image: gluwa/creditcoin-processor:1.8
    container_name: creditcoin-processor
    depends_on:
      - validator
      - settings-tp
    entrypoint: ./bin/ccprocessor-rust -E tcp://validator:4004 -G tcp://gateway:55555 -vvv
    stop_signal: SIGKILL
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"

  consensus:
    image: gluwa/creditcoin-consensus:1.8
    container_name: consensus
    depends_on:
      - validator
    entrypoint: ccconsensus -E tcp://validator:5050 -vvv

  gateway:
    image: gluwa/creditcoin-gateway:1.8
    container_name: creditcoin-gateway
    expose:
      - 55555
    ports:
      - 55555:55555
    secrets:
     - source: gateway_config
       target: /home/Creditcoin/Gateway/appsettings.json
    entrypoint: ./ccgateway -v
    stop_signal: SIGKILL
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"

secrets:
  gateway_config:
    file: ./gatewayConfig.json
  rest_api_logging:
    file: ./rest_api-log_config.toml
  validator_logging:
    file: ./validator-log_config.toml

volumes:
  validator-block-volume:
  validator-key-volume:
