#	Copyright(c) 2018 Gluwa, Inc.
#
#	This file is part of Creditcoin.
#
#	Creditcoin is free software: you can redistribute it and/or modify
#	it under the terms of the GNU Lesser General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.
#	
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#	GNU Lesser General Public License for more details.
#	
#	You should have received a copy of the GNU Lesser General Public License
#	along with Creditcoin. If not, see <https://www.gnu.org/licenses/>.

version: "3.7"

services:

  settings-tp:
    image: hyperledger/sawtooth-settings-tp:1.0
    container_name: sawtooth-settings-tp-default
    read_only: true
    tmpfs:
      - /var/log/sawtooth
    depends_on:
      - validator
    entrypoint: settings-tp -C tcp://validator:4004
    stop_signal: SIGKILL
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"

  validator:
    image: gluwa/creditcoin-validator:1.7
    container_name: sawtooth-validator-default
    read_only: true
    tmpfs:
      - /var/log/sawtooth
    volumes:
      - type: volume
        source: validator-block-volume
        target: /var/lib/sawtooth/
      - type: volume
        source: validator-key-volume
        target: /etc/sawtooth/keys/
    expose:
      - 4004
      - 8800
    ports:
      - 4004:4004
      - 8800:8800
    secrets:
     - source: validator_logging
       target: /etc/sawtooth/log_config.toml
    entrypoint: |
        bash -c 'if [[ ! -f /etc/sawtooth/keys/validator.pub ]]
            then 
                echo "First run"
                sawadm keygen
            fi
            sawtooth-validator \
                --endpoint tcp://[insert.your.ip]:8800 \
                --bind component:tcp://eth0:4004 \
                --bind network:tcp://eth0:8800 \
                --peering dynamic \
                --seeds tcp://node-000.creditcoin.org:8800 \
                --seeds tcp://node-001.creditcoin.org:8800 \
                --seeds tcp://node-002.creditcoin.org:8800 \
                --seeds tcp://node-003.creditcoin.org:8800 \
                --maximum-peer-connectivity 5 \
                --scheduler parallel'
    stop_signal: SIGKILL
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "100m"

  rest-api:
    image: gluwa/sawtooth-rest-api:1.7
    container_name: sawtooth-rest-api-default
    read_only: true
    tmpfs:
      - /var/log/sawtooth
    ports:
      - 8008:8008
    secrets:
     - source: rest_api_logging
       target: /etc/sawtooth/log_config.toml
    depends_on:
      - validator
    entrypoint: sawtooth-rest-api -C tcp://validator:4004 --bind rest-api:8008
    stop_signal: SIGKILL
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"

  processor:
    image: gluwa/creditcoin-processor:1.7
    container_name: creditcoin-processor
    read_only: true
    depends_on:
      - validator
      - settings-tp
    entrypoint: ./ccprocessorLinux.out tcp://validator:4004 tcp://gateway:55555
    stop_signal: SIGKILL
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"

  gateway:
    image: gluwa/creditcoin-gateway:1.7
    container_name: creditcoin-gateway
    read_only: true
    expose:
      - 55555
    ports:
      - 55555:55555
    secrets:
     - source: gateway_config
       target: /home/Creditcoin/Gateway/appsettings.json
    entrypoint: ./ccgateway
    stop_signal: SIGKILL
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"

secrets:
  gateway_config:
    file: ./gatewayConfig.json
  rest_api_logging:
    file: ./rest_api-log_config.toml
  validator_logging:
    file: ./validator-log_config.toml

volumes:
  validator-block-volume:
  validator-key-volume:
